values:
  - name: "Cores"
    display_name: "How many CPU cores to allocate."
    uint_value: 4
    display_category: "Resources"
  - name: "Memory"
    display_name: "How much memory to allocate."
    string_value: "8gb"
    display_category: "Resources"

  - name: "HomeVolume"
    display_name: |
      [optional] Storage volume used as your home directory. Will be mounted at /home/user.
      Use to house a persistent R library, settings, etc. If not set (the default), an
      ephemeral home directory will be created and any changes made in the home directory
      will not persist.
    string_value: ""
    display_category: "Storage"
  - name: "DataVolume"
    display_name: "[optional] Storage volume for user data and R workspace files."
    string_value: ""
    display_category: "Storage"
  - name: "ScratchVolume"
    display_name: "[required] Volume used for temporary data."
    string_value: "volume://user/ephemeral"
    display_category: "Storage"

  - name: "ContainerImage"
    display_name: |
      Container image to use. This workflow assumes that a image from
      the Rocker project is used
    string_value: "docker://rocker/tidyverse:4.5.2"
    display_category: "Container"

  - name: "ServiceScope"
    display_name: |
      [required] Who can access this Rstudio server instance. Defaults to 'user'
    string_value: user
    options_input:
      options: [user, group, organization]
    display_category: "Access"
